version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT_0}:3000" 
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn run run:dev
