FROM node:lts-alpine AS deps
WORKDIR /app
COPY yarn.lock package.json ./
RUN apk add --no-cache git python3 py3-setuptools make g++ && \
    yarn install

FROM deps AS build
WORKDIR /app
ARG GRAPHQL_API_ENDPOINT
COPY . .
RUN yarn run build:prod

FROM nginx:stable-alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx-ufps.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 
ENTRYPOINT ["nginx", "-g", "daemon off;"]